//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyQuanTraSua.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHD
    {
        public int MaHD { get; set; }
        public string MaMon { get; set; }
        public string Ban { get; set; }
        public int Gia { get; set; }
        public int SoLuong { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual MENU MENU { get; set; }
    }
}
