//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyQuanTraSua.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        public int MaGio { get; set; }
        public string MaMon { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaHD { get; set; }
        public string MaGH { get; set; }
        public string MaKM { get; set; }
    
        public virtual GIAOHANG GIAOHANG { get; set; }
        public virtual HOADON HOADON { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual MENU MENU { get; set; }
    }
}
