//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyQuanTraSua.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MENU()
        {
            this.CHITIETHDs = new HashSet<CHITIETHD>();
            this.GIOHANGs = new HashSet<GIOHANG>();
        }
    
        public string MaMon { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public string TenMon { get; set; }
        [Required(ErrorMessage = "Không thể bỏ trống!")]

        public int Gia { get; set; }
        [Required(ErrorMessage = "Không thể bỏ trống!")]

        public int SoLuongDaBan { get; set; }

        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHD> CHITIETHDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        public virtual LOAIMENU LOAIMENU { get; set; }
    }
}
