//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyQuanTraSua.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANCA
    {
        public int MaNV { get; set; }
        public int MaCN { get; set; }
        public Nullable<System.DateTime> NgayLamViec { get; set; }
        public Nullable<int> GioLamViec { get; set; }
    
        public virtual CHINHANH CHINHANH { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
