//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyQuanTraSua.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class QUANLY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUANLY()
        {
            this.CHINHANHs = new HashSet<CHINHANH>();
        }
    
        public int MaQL { get; set; }
        public string TenQL { get; set; }
        [Required(ErrorMessage = "Không thể bỏ trống!")]

        public string Email { get; set; }
        [Required(ErrorMessage = "Không thể bỏ trống!")]

        public int Tuoi { get; set; }
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "Không thể bỏ trống!")]

        public string SDT { get; set; }
        [Required(ErrorMessage = "Không thể bỏ trống!")]

        public int Luong { get; set; }
        [Required(ErrorMessage = "Không thể bỏ trống!")]

        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHINHANH> CHINHANHs { get; set; }
        public virtual TAIKHOANQL TAIKHOANQL { get; set; }
    }
}
