//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyQuanTraSua.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TAIKHOANKH
    {
        public string UserName { get; set; }

        public string Pass { get; set; }

        public int MaKH { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
